services:
    client:
        build:
            context: ./src
        ports:
            - '3000:80'

    server:
        build:
            context: ./server
        ports:
            - '3001:3001'
        environment:
            - MONGODB_URI=mongodb://mongo:27017/auto-landing
        depends_on:
            - mongo

    mongo:
        image: mongo
        ports:
            - '27017:27017'
